### ISSUE TITLE
how do I fix (harbor cmd) not working? 

### ISSUE THREAD

**Issue by ColumbusAI** [av/harbor#11]
![image](https://github.com/user-attachments/assets/7e3dbb3c-a0ee-4693-8eba-c2a71195cbc1)

My goal is to modify the VLLM docker to mount my local model folder so it can see those models. I am using Debian in WSL2.

**Comment by av** [comment]
Hey, you'll need to use the command substitution for these to work as expected:

```bash
harbor cmd litellm
echo $(harbor cmd litellm)
eval "$(harbor cmd litellm) run litellm --help"
```

`vllm` service already has a configurable cache folder which can be modified via Harbor CLI:
```bash
# See current path
harbor config get vllm.cache

# Point to your custom location
harbor config set vllm.cache ~/Downloads/vllm
```

Also, `vllm` service was fixed and no longer requires `litellm` in order to be connected to Open WebUI - works on its own.

If you intend to always run `vllm` (or other services) - consider adding them to the defaults
```bash
harbor defaults add vllm

# [Optional] if intended
harbor defaults rm ollama
```

**Comment by ColumbusAI** [comment]
@av you are the man! thanks Ivan
