### ISSUE TITLE
Harbor install script / update defaults to 1.9

### ISSUE THREAD

**Issue by Pokora22** [av/harbor#21]
Hey. Just wanted to let you know when using that script, the installation (and updates using 'harbor update') list version 1.9 as the latest.
I'm running this on Ubuntu 22.04 LTS. Git listing versions sorts them alphabetically, so 1.24 is lower than 1.9 when I run the command.

Minor issue that can be circumvented by running the install manually + replacing instead of script/update.

PS. This project is amazing. Makes trying stuff out so easy and clean!

**Comment by av** [comment]
Thank you so much for the feedback and for trying out Harbor!

Current behavior is less than ideal and needs to be fixed, there are also problems with the shallow clone that is done by the intstall

**Comment by av** [comment]
I've prepared a possible fix [here](https://github.com/av/harbor/commit/6c61d1a5ae3d9952f120b7fbaca22c79e1e5629f), the only question is MacOS compat

**Comment by av** [comment]
The fix was released in scope of [v0.1.27](https://github.com/av/harbor/releases/tag/v0.1.27)

I'll keep this issue open for visibility, since it essentially prevents anyone from upgrading unless they know that there's a problem.

Workarounds:
- Try updating with `harbor update --latest`
- Manually update to latest with git CLI
- Update via re-executing the install script
- Re-install Harbor

**Comment by av** [comment]
Closing, since I think enough time passed for most of the users to be on versions where this problem was fixed
