### ISSUE TITLE
[question] Unable to upgrade Dify.AI

### ISSUE THREAD

**Issue by ZacharyKehlGEAppliances** [av/harbor#25]
When I attempt to pull the latest Dify.AI build I only pull` 0.6.16`, am I missing a command or process to update it to the latest?

Also just want to say I am in awe with how easy it is to use this software. Incredible work!

**Comment by av** [comment]
Thanks for trying out Harbor!

Dify was one of the more complex projects to integrate, so unfortunately it comes with a pinned version. It can be bumped manually via `harbor config set dify.version <version number>`. Unfortunately, due to how project is setup it's not guaranteed to continue working after the update, so you might need to test a few versions.

All of the Dify config options in Harbor can be queried with:
```bash
 user@os:~$ ▼ h config list | grep DIFY
DIFY_HOST_PORT                 33961
DIFY_DB_HOST_PORT              33962
DIFY_D2O_HOST_PORT             33963
DIFY_VERSION                   0.6.16
DIFY_SANDBOX_VERSION           0.2.1
DIFY_WEAVIATE_VERSION          1.19.0
DIFY_VOLUMES                   ./dify/volumes
DIFY_BOT_TYPE                  Chat
DIFY_OPENAI_WORKFLOW           
```

**Comment by ZacharyKehlGEAppliances** [comment]
Ahh understandable. Thank you for the quick response!

**Comment by av** [comment]
No pbs, mentioned this in Dify docs:
https://github.com/av/harbor/wiki/2.3.3-Satellite:-Dify#updating-dify
