### ISSUE TITLE
Add Langflow

### ISSUE THREAD

**Issue by ZacharyKehlGEAppliances** [av/harbor#82]
Langflow is a low-code app builder for RAG and multi-agent AI applications. It’s Python-based and agnostic to any model, API, or database.

- Python-based and agnostic to models, APIs, data sources, or databases.
- Visual IDE for drag-and-drop building and testing of workflows.
- Playground to immediately test and iterate workflows with step-by-step control.
- Multi-agent orchestration and conversation management and retrieval.
- Free cloud service to get started in minutes with no setup.
- Publish as an API or export as a Python application.
- Observability with LangSmith, LangFuse, or LangWatch integration.
- Enterprise-grade security and scalability with free DataStax Langflow cloud service.
- Customize workflows or create flows entirely just using Python.
- Ecosystem integrations as reusable components for any model, API or database.

**Comment by ZacharyKehlGEAppliances** [comment]
Honestly right now I have been using Dify.ai and love it. It just has a lack of connectors. Langflow has some really great connectors and is supported by the langchain team. It also seems that their RAG implementation is a bit more advanced than Dify but I havent looked into it too much. 

The only thing I have found from Langflow that is a major negative is there is no direct support for passing the API to Openwebui

**Comment by ZacharyKehlGEAppliances** [comment]
Also I have started work on importing it here. It seems pretty successful, I am just having issues handling harbor url and harbor open.

https://github.com/ZacharyKehlGEAppliances/harbor-langflow

**Comment by av** [comment]
Hey 👋🏻 

- Thanks for trying out Harbor and for the suggestion! 
- Langflow was planned eventually, and Flowise as well, we do want to expand on satellites with visual LLM workflows, I've been using Dify/LitLytics quite a bit, we also have n8n (a bit cumbersome to configure), and omnichain already available meanwhile the services above are in progress
- the PR looks awesome! The URL/Open problem might be coming from the wrong network name (should be `harbor-network`, as well as no need to redefine it), while developing and adding new vars to the default profile, you can run `harbor config update` to sync them back to the current `.env`, otherwise nothing looks fishy enough to be an immediately obvious cause

**Comment by av** [comment]
JFYI, Flowise was just added in [v0.2.18](https://github.com/av/harbor/releases/tag/v0.2.18) (very nice DevX, functionality is great too), @ZacharyKehlGEAppliances , granted you have a WIP for LangFlow integration - please feel free to open a PR whenever ready, I'll avoid adding it myself to avoid conflicts

**Comment by ZacharyKehlGEAppliances** [comment]
@av appreciate it! I am fixing the `harbor-network` issues right now and should have something ready here soon!

**Comment by ZacharyKehlGEAppliances** [comment]
@av https://github.com/av/harbor/pull/86#issue-2699442309

**Comment by av** [comment]
The PR was merged, I tested everything and added the docs here:
https://github.com/av/harbor/wiki/2.3.32-Satellite:-LangFlow

Will be released later today, thanks again for the contribution!
