### ISSUE TITLE
didn't see in docs -- how do I fix if a container is unhealthy?

### ISSUE THREAD

**Issue by ColumbusAI** [av/harbor#9]
$ harbor up vllm litellm
[+] Running 4/5
 ✔ Network harbor_harbor-network  Created                                     0.0s
 ⠸ Container harbor.webui         Waiting                                     6.1s
 ✔ Container harbor.vllm          Healthy                                     5.1s
 ✔ Container harbor.litellmdb     Healthy                                     5.1s
 ✔ Container harbor.litellm       Healthy                                     5.1s
container harbor.webui is unhealthy

**Comment by av** [comment]
Thanks for trying out Harbor!

Right now WebUI health check is a bit too aggressive in order to reduce the service startup wait, it may often result in webui service not passing it in time. The service itself should be healthy once started, though. I'll relax the health check parameters with next release so that it's not as frequent

**Comment by av** [comment]
One other thing not reflected in docs - vllm doesn't require litellm anymore, can run directly with the webui

**Comment by ColumbusAI** [comment]
thank you! you rock :-D

**Comment by av** [comment]
Implemented in [v0.1.8](https://github.com/av/harbor/releases/tag/v0.1.8)
